name: CI/CD Workflow

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11 and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: 'x64'
          
      - name: Install Maven
        run: sudo apt update && sudo apt install -y maven    

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Install Docker
        run: |
          # Install Docker on the self-hosted runner (for Ubuntu)
          sudo apt update
          sudo apt install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          # Add the current user to the 'docker' group to use Docker without 'sudo'
          sudo usermod -aG docker $USER
        shell: bash

      - name: Build & push Docker image
        run: |
          # Build the Docker image with name 'newDemo'
          docker build -t newDemo .
          docker tag newDemo:latest sharan7898/newDemo:latest  # Replace 'username' with your Docker Hub username or registry
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push sharan7898/newDemo:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Docker container
        run: |
          # Run the Docker container from the image
          docker run -d -p 8080:8080 --name my_container sharan7898/newDemo:latest  # Replace 'username' with your Docker Hub username or registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
